### ISSUE TITLE
Refactor code based on rooms

### ISSUE THREAD

**Issue by resir014** [resir014/screeps#14]
Reference: https://github.com/ErikVanNorstrand/screeps-typescript

Right now the way we implement everything relies on us having only one room only. So we need to refactor so that everything's not room-dependent.

Trying to fix this may also help us in fixing #7.

**Comment by ChaoticWeg** [comment]
Correct me if I'm wrong here, I'm still getting used to TypeScript and ES6 conventions, having converted myself from plain old Node and JS.

Do we need to worry about the fact that `CreepManager`, `StructureManager`, etc. appear overwrite their globals for each room? I.E. (from `CreepManager`) -

```
export let creeps: Creep[];

function _loadCreeps(room: Room): void {
  creeps = room.find<Creep>(FIND_MY_CREEPS);
  // -snip-
}
```

instead of something like:

```
export let creeps: Creep[];

function _loadCreeps(room: Room): void {
  creeps.push(room.find<Creep>(FIND_MY_CREEPS));
  // -snip-
}
```

**Comment by resir014** [comment]
From the logic I had when writing it, using the `.push()` method might not be refreshed whenever it's instantiated every loop. Plus, `.push()` will most likely only work when we instantiated `creeps` as an empty array (`[]`).

I'm open to second opinions about this though
