### ISSUE TITLE
Better autospawning logic

### ISSUE THREAD

**Issue by resir014** [resir014/screeps#6]
Currently, the `canCreate*()` method is unused because using that somehow doesn't cause the creeps to autospawn if needed in some cases. We need to improve this.

**Comment by ChaoticWeg** [comment]
When testing our script in a new simulation room, there comes a point where there are a ton of upgraders and builders, and not enough harvesters to keep up with the energy demand.  This is probably due to a lack of awareness in the autospawning logic.  I will try to make the autospawning logic more aware of creep types and their relative priorities.

**Comment by ChaoticWeg** [comment]
I am doing some tweaking on my local copy, but I don't think I'll have any success here in the next few hours. I'm thinking we should go ahead with merging #15, and converging with Erik's repo, and then I'll get to work on it.

**Comment by resir014** [comment]
Closing this in favour of #7.
